apiVersion: ENC[AES256_GCM,data:AwE=,iv:fL/s5wh/vMbuZ2XHqSlCwjdpWSCHmO7ZFsMnk2QYm3w=,tag:pGMJIGdqQdVBj1b9LvU52Q==,type:str]
kind: ENC[AES256_GCM,data:VzVYbF2L,iv:BxWThCjspLs5Y0PBU3t3pfQRGS9C/sXNA6iLEUsNhyg=,tag:uo4IyvHTs9OBS//HpPoW+Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:E/k768oIAA==,iv:Phlf7hAGrC7BFhAw9/YNE3LN6P+7w1X0hIdZR1XGadA=,tag:HsujcNK1QRadC2V05P68oA==,type:str]
type: ENC[AES256_GCM,data:XWWyZreT,iv:C4tRurnhHS7/2ZWL4gbUAcwRVgYwpCatLl04Eh+t8LM=,tag:c5On4aH4uW+Ma5Z0iCRNAg==,type:str]
stringData:
    username: ENC[AES256_GCM,data:E04OSPQur5udrOhRe+jdOed3+FKWZuB4,iv:dKc0wqSWtt7EICC66VAZqS/l17WhPswXleCpzPJFCS0=,tag:xzgjy+SG/XV3PPVL6V6qBQ==,type:str]
    password: ENC[AES256_GCM,data:hUwD5+HMXswSrzhCY3DIuGSKpZmJB4/n,iv:IzZTNt0ZQg0ryUZsBm375h0nSfwVDHVQRmQx4a8S8Do=,tag:HeLpflPU3uLf892GgsfP+w==,type:str]
sops:
    age:
        - recipient: age1p6c59j97s0nf6enr4fmwnhwn508s92eyvwtc2wmd24wkpecr3drshgt0n2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxZHBjWFVGNWZuVmplUU42
            NW54SDlqRHFnUVB2T2NjeW5YSGdsaWZQZlNrCnVHSm50UEkzcFNmQUhXTTZvTENj
            elc4dHkrWUN6dTV1S2VGTlg1RFljWDgKLS0tIFNmQ3B3V095ZExPcTN2Y2pEV2Vw
            eTRuRG9sS0ErZUpFKzNoakF6VGtVVGsKNjf3d6eleITzJziYjorpJvHuIes5GSGo
            6dPP14QSGWLZchd2jMfaBYRte6l0/f6pSwll7hCgp5s7+SU2LVE6qw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-10T16:49:12Z"
    mac: ENC[AES256_GCM,data:J2jpUMluhiXcSOeccT7lKGpy+ra7pIJ5qvaKAP1L9w8muNNFLOK/fBZ6AKCKHCayXtejwHlspApyWdCI4Z27Wlbw5O2BLuC0Lqunm5oM3t4ATwqhgcM2SFVh0pNFP3h5NS1DnURA6NAUixODg8FutWEVnkcwXT4J3aHVXGvLNF0=,iv:1peeL1pfhNP60HONOziTzz/bePPC86vo2QGmtNfQbf0=,tag:vlUo7Sl7bhHrVycSvQCVDg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
