apiVersion: ENC[AES256_GCM,data:3TE=,iv:If8Y8ItLy2i2fNtrjLnBWSlACS2vKgPE7Og/VfrFcmw=,tag:y9QWqQ5opVzFrrQPe7T+wg==,type:str]
kind: ENC[AES256_GCM,data:/rh8gqkD,iv:B+7yPOIBGpfbmwVwAVLIxBxaqKRTgJ7mshMX7fGowMg=,tag:W+zju/clQuG/WTRlgN83hA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:yxd7efx/I8IS9KMlducKaBbWN3qkme8=,iv:8XEC6nD/KUc25I2S9LaBdxlcdjQsOakbwdAckQQbvSY=,tag:egfLkXGslazr80FggfekiQ==,type:str]
type: ENC[AES256_GCM,data:8ubijvsX,iv:gEdrn88S34jheptyFe3GTP6eRnwGw3c3DanuAaFHG48=,tag:444fK4lxAacxfwihZLUcSA==,type:str]
stringData:
    credentials.json: ENC[AES256_GCM,data:gNwno8oz8wNPNLugz54IUENvJLNgPmcs3jfBJhQyqsGQhDy4qTO62DxjXG6x21m3GmpcNtFr08I3JU3zHV+r0K0rja0x6E0TRqfP0xbJCU/cmcGNhGFzA9KNlIwLFZWD4KY8Kgdj7114RNtmGLmwa/XuIbg7i+49N+DkqgePBk1r5BjAvjebnlWbwm1f0gmg/SDG875JZV/YHLzwewllzQ4W,iv:wgkbH9GjPzcf5/y/wsSy0cQJUT9WxtQyk6QsHmeOcik=,tag:7p7gBaDMtcZjsG9iKhI4Og==,type:str]
sops:
    age:
        - recipient: age1p6c59j97s0nf6enr4fmwnhwn508s92eyvwtc2wmd24wkpecr3drshgt0n2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlSHErNXZxRHdsN1g4bFdi
            VUg0ckdpTEJsYzdZUk5KcGlkWnNWekcwSUFrClQzMk5JY0pVczdzWTVjWEFWZjE2
            OTVTS3EwQlMvVDlPVGhNa1dxZXFSUTgKLS0tIERiS2tENGhUSkN0OE96akZzNWhD
            d0twWVV6d0R6bCt5RFJYM0t2VTllVDAKVEWHC9Dein0YnCvKY8fBuSaJ4tXK274q
            4kV/5sYTAh9gszaKsiqo8pxscZYnOKrveMme8sv2ubw2XoIltsK01w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-09T15:29:13Z"
    mac: ENC[AES256_GCM,data:Z9F6ah7prAI+mgo3CGWOJ01LEvcPp3xiyUud7iuAryN7LmhXQAoZIvXXS0zL0ucQ1C/R41chbDvW66vdfwTw8HkIP4nEejnd+9n4AZSK8xIoRDNnAMrs81xg+C0BYbdaEzoMUWeeQWeLq+ZD6L8JG0H+qnmBSzlwWUxSQSOBMQo=,iv:wkHevF2p7MgJVoqTFTGlxh8xvr7d8hBKN1ziLblHcLw=,tag:g3L97jU2/EJ+NMh18yQa4A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
